/**
 * Hex-mosaic loader & per-hex animation timing.
 *
 * The four focus-area mosaics in `public/images/fa2/mosaics/<slug>.svg` are
 * generated by `scripts/generate-hex-mosaics.mjs` as a flat list of
 * `<polygon>` hexes. To animate individual tiles on hover (the "signal
 * awakens" / per-area wave effect), we read each SVG at module-load time,
 * parse out the polygons, and assign each a CSS animation-delay so a wave
 * sweeps across the cloud in a pattern that matches its focus area:
 *
 *   shield  (DHR)   → left→right sweep         (signal scan)
 *   hexagon (E&G)   → radial out from centroid (network rebalancing)
 *   neural  (AI)    → pseudo-random sparkle    (neuron activations)
 *   brain   (Neuro) → top→bottom sine wave     (brainwave / EEG)
 *
 * The helper is server-only — it uses node:fs synchronously at import time
 * and caches the parsed result. Consumers are server components.
 */
import { readFileSync } from "node:fs"
import { join } from "node:path"

export type HexPattern = "shield" | "hexagon" | "neural" | "brain"

export type ParsedHex = {
  /** Original `points="..."` string from the SVG, unchanged. */
  points: string
  /** `rgb(r,g,b)` fill. */
  fill: string
  /** Per-hex base opacity (0..1) — drives the cloud falloff. */
  opacity: number
  /** ms delay applied to the hover keyframe so the wave sweeps. */
  delayMs: number
}

export type ParsedMosaic = {
  viewBox: string
  width: number
  height: number
  polygons: ParsedHex[]
}

const POLY_RE =
  /<polygon\s+points="([^"]+)"\s+fill="([^"]+)"\s+fill-opacity="([^"]+)"\s*\/>/g
const SVG_RE = /<svg[^>]*viewBox="([^"]+)"[^>]*width="([^"]+)"[^>]*height="([^"]+)"/

const cache = new Map<string, ParsedMosaic>()

/** Total ms over which a hover wave fans across the entire cloud. */
const WAVE_SPAN_MS = 750

/**
 * Soft edge-fade band: fraction of cluster width/height (measured from each
 * non-bottom edge) over which hex base-opacity ramps from FADE_FLOOR → 1
 * via a smoothstep curve. Hexes inside this band gradually dissolve toward
 * the page background so the cluster reads as a soft cloud rather than a
 * hard silhouette.
 *
 * The bottom edge is intentionally excluded — that's where the cluster meets
 * the white card panel and should stay crisp.
 *
 * `FADE_FLOOR` is the minimum opacity multiplier applied at the very outer
 * edge: even the outermost hexes stay visible as a faint "ghost layer"
 * rather than vanishing entirely. Keeps the dissolve looking soft and
 * organic instead of cropping the silhouette away.
 *
 * Tuned by eye: a wide band (0.40) plus a non-zero floor (0.12) gives a
 * long, gentle gradient from bright core to barely-there outer halo.
 */
const FADE_BAND = 0.4
const FADE_FLOOR = 0.12

/** Cubic smoothstep — 0 at t≤0, 1 at t≥1, S-curve in between. */
function smoothstep(t: number): number {
  if (t <= 0) return 0
  if (t >= 1) return 1
  return t * t * (3 - 2 * t)
}

export function loadHexMosaic(slug: string, pattern: HexPattern): ParsedMosaic {
  const key = `${slug}|${pattern}`
  const cached = cache.get(key)
  if (cached) return cached

  const file = join(
    process.cwd(),
    "public",
    "images",
    "fa2",
    "mosaics",
    `${slug}.svg`,
  )
  const raw = readFileSync(file, "utf8")

  const meta = SVG_RE.exec(raw)
  if (!meta) {
    throw new Error(`hex-mosaic: could not parse <svg> meta in ${slug}.svg`)
  }
  const viewBox = meta[1]
  const width = parseFloat(meta[2])
  const height = parseFloat(meta[3])

  type Raw = {
    points: string
    fill: string
    opacity: number
    cx: number
    cy: number
  }
  const polys: Raw[] = []
  POLY_RE.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = POLY_RE.exec(raw)) !== null) {
    const points = m[1]
    const fill = m[2]
    const opacity = parseFloat(m[3])
    // Centroid = mean of the 6 vertices. Good enough for delay-mapping.
    const coords = points
      .trim()
      .split(/\s+/)
      .map((p) => p.split(",").map(Number) as [number, number])
    let sx = 0
    let sy = 0
    for (const [x, y] of coords) {
      sx += x
      sy += y
    }
    polys.push({
      points,
      fill,
      opacity,
      cx: sx / coords.length,
      cy: sy / coords.length,
    })
  }

  // Compute bounds once for normalisation.
  let minX = Infinity
  let maxX = -Infinity
  let minY = Infinity
  let maxY = -Infinity
  for (const p of polys) {
    if (p.cx < minX) minX = p.cx
    if (p.cx > maxX) maxX = p.cx
    if (p.cy < minY) minY = p.cy
    if (p.cy > maxY) maxY = p.cy
  }
  const w = maxX - minX || 1
  const h = maxY - minY || 1

  const polygons: ParsedHex[] = polys.map((p, i) => {
    const nx = (p.cx - minX) / w // 0..1, left → right
    const ny = (p.cy - minY) / h // 0..1, top → bottom

    // Edge fade — multiply base opacity by a soft falloff toward the
    // nearest non-bottom edge so the cluster dissolves into a faint halo
    // at the top, left, and right. The bottom is left full-strength because
    // that's the design line where the cloud meets the card. The fade
    // never reaches zero (FADE_FLOOR floor), so the outermost hexes still
    // ghost-render rather than vanishing.
    const distTop = ny
    const distLeft = nx
    const distRight = 1 - nx
    const minEdgeDist = Math.min(distTop, distLeft, distRight)
    const edgeT = Math.min(1, minEdgeDist / FADE_BAND)
    const fade = FADE_FLOOR + (1 - FADE_FLOOR) * smoothstep(edgeT)
    const fadedOpacity = p.opacity * fade
    let t = 0 // 0..~1 wave-progress for this hex

    switch (pattern) {
      case "shield": {
        // Clean L→R sweep — the signal scans across the shield.
        t = nx
        break
      }
      case "hexagon": {
        // Radial out from cluster centroid — the network rebalances.
        const dx = nx - 0.5
        const dy = ny - 0.5
        // Normalise so corner = 1.
        t = Math.min(1, Math.hypot(dx, dy) / Math.SQRT1_2)
        break
      }
      case "neural": {
        // Deterministic pseudo-random — neurons fire in no particular order.
        const s = Math.sin(i * 12.9898 + 78.233) * 43758.5453
        t = s - Math.floor(s)
        break
      }
      case "brain": {
        // Top→bottom slow wave with a gentle horizontal phase wobble.
        t = ny + Math.sin(nx * Math.PI * 2) * 0.08
        // Clamp to keep delays inside the wave window.
        if (t < 0) t = 0
        else if (t > 1) t = 1
        break
      }
    }

    return {
      points: p.points,
      fill: p.fill,
      opacity: fadedOpacity,
      delayMs: Math.round(t * WAVE_SPAN_MS),
    }
  })

  const result: ParsedMosaic = { viewBox, width, height, polygons }
  cache.set(key, result)
  return result
}
